Support for collapsed menu items and external links
braintree/jsdoc-template pull request #19
Opened 2018-10-12 20:02 UTC by arianics

![screen shot 2018-10-12 at 12 55 19 pm](https://user-images.githubusercontent.com/2319251/46891255-259a2580-ce1e-11e8-9359-6dbe1ea46f86.png)

Pictures are worth a thousand words :)
The "References" section was added to allow for linking to outside resources but also linking back to GitBook or similar documentation projects.

Let us know if we need to make any changes.

Best,

2018-10-15 15:15 UTC, crookedneighbor requested changes
Just a few things:

* Can you go into more detail about what the css fixes are? Looks mostly like you just adjusted some padding and margins, but were there actual problems with the template?
* Can you add documentation for using these new properties (collapse and resources) in the README?

2018-10-15 15:15 UTC, crookedneighbor commented on tmpl/layout.tmpl
> +        References
Can we call this resources instead of references?

2018-10-15 15:15 UTC, crookedneighbor commented on CHANGELOG.md
> +3.3.0
Put `unreleased` here. When we actually do the tagging, we'll change it to `3.3.0`

2018-10-15 15:15 UTC, crookedneighbor commented on package.json
> +  "version": "3.3.0",
Please revert this change.

2018-10-16 06:08 UTC, arianics commented
Hey @crookedneighbor ,

I just pushed the requested changes.

The "css fixes" refers to the missing `;` in the following snippet. `static/styles/collapse.css` only loads when collapse is enabled and adjusts paddings/margins for this mode.
https://github.com/braintree/jsdoc-template/blob/9ac837f2a774610c3de55431454777ae2419ba11/static/styles/jsdoc-default.css#L362

2018-10-16 12:29 UTC, crookedneighbor approved these changes
Ahh, i see. Should have looked at the file names closer. Somehow totally missed the changes to the default css file.

2018-10-16 12:35 UTC, crookedneighbor commented
I think the links should appear on hover, so you don't need to use the parent link to see the child links. If you want to do that as part of this PR, great. If not, we can do it after it's merged.

Let me know which you decide.

2018-10-16 15:33 UTC, arianics commented
Let me try it and see how it looks. I’ll let you know today. 

Also, What do you think about keeping the links in mobile menu expanded?

2018-10-16 16:04 UTC, crookedneighbor commented
Yeah, it should probably be fully expanded on mobile.

2018-10-16 18:20 UTC, arianics commented
I added a media query to collapse.css to only apply the rules on larger displays.

I also have a branch on my forked repo for the hover to expand feature. Let me know what you think.
https://github.com/AgeOfLearning/jsdoc-template/tree/menu-hover

2018-10-19 01:34 UTC, crookedneighbor commented
Added in the hover css, but left out the changes to the default css file.

Closed with v3.3.0

2018-10-19 01:34 UTC, closed without merging