Show package version in title
braintree/jsdoc-template pull request #21
Opened 2019-07-12 21:56 UTC by rwwagner90

It took me a long time to figure out how to do this, due to there being no documentation on how to work with jsdoc templates anywhere. I thought perhaps showing the version in the title might be nice, for versioned docs. Thoughts?

2019-07-16 21:06 UTC, gesa requested changes
__big caveat that i don't know this source code super well so i may have made some assumptions i shouldn't have__

A couple thoughts. If you want to go the easy way, scrap any publish.js changes and just expect the version to come in via the JSDoc conf file. I'm not _entirely_ certain we'd merge that in? But it'd work on your fork for sure.

In our [web drop-in package](https://github.com/braintree/braintree-web-drop-in/blob/b9d83716eed7f1423573d70d6d8383ea31415097/gulpfile.js#L190), we sorta fake having the package's version number everywhere using string replacement. If you're interested in utilizing the overall package's `@version` JSDoc tag (which suddenly I am) on every generated page you'll have to rethink your strategy. The object passed as a callback param when looping through the TaffyDB using `.each()` _will_ have a version property *if* `@version` appears in that document. The problem is who knows how many functions somehow have a legacy version number because someone used `@version` instead of `@since` or something. 

Anyway in theory you could find specifically the _package_ version and once you do, use it everywhere. Doing that I think you could generate the documentation you're looking for.

Also, just generally, good call-out. The version number is frequently littered all over our docs but not in a header.

2019-07-16 21:06 UTC, gesa commented on tmpl/layout.tmpl
> +      <?js= package.version ?>
```suggestion
      v<?js= templates.version ?>
```

What about passing the version in via the `templates` object in jsdoc's conf file? (additionally, I'd probably eliminate the newline here and tack it on to the end of L99)

2019-07-16 21:06 UTC, gesa commented on publish.js
> +  var packageInfo = (find({kind: 'package'}) || [])[0];
I'm not convinced there's a scenario where there _is_ a `version` property on this object. Or at least, not yet (see longer comment)

2019-07-16 23:27 UTC, rwwagner90 commented
Hi @gesa thanks for the review! If you have a `package.json` with a `version` defined, I believe this will always be populated. I am using this technique myself on https://shepherdjs.dev/docs/

2019-07-17 00:04 UTC, gesa commented
Using this branch on braintree web drop-in did not populate that string.

2019-07-17 01:31 UTC, rwwagner90 commented
@gesa can you point me to the repo you tried it on please? If you have a package.json in the repo, and you include it in your files in your jsdoc config, it *should* work.

2019-07-17 22:29 UTC, gesa commented
So I had run it on https://github.com/braintree/braintree-web-drop-in/ not totally registering that package.json was not included in the JSDoc config. Today I spent an hour or so wondering how it has _ever_ worked because the smallest change torpedoes JSDoc generation (including adding package via config or CLI) and also there's a symlink in there that _definitely_ shouldn't work as far as i understand `fs.symlink()` so I'm just gonna back away and come back to this after I return to work at the end of July.

2019-07-18 00:10 UTC, rwwagner90 commented
Ah gotcha. Feel free to ping me when you get back, and we can take another look.

2019-07-23 21:44 UTC, crookedneighbor commented on publish.js
> +  var packageInfo = (find({kind: 'package'}) || [])[0];
Agreed, I just tried it on the braintree-web and braintree-web-drop-in repos and there was no version property.

(added the prefixed `v` below so you can see that it is missing the version)

<img width="293" alt="Screen Shot 2019-07-23 at 4 44 02 PM" src="https://user-images.githubusercontent.com/2916945/61749745-1b239980-ad69-11e9-80c0-d2c2d824c62a.png">

2019-07-24 00:16 UTC, rwwagner90 commented on publish.js
> +  var packageInfo = (find({kind: 'package'}) || [])[0];
@crookedneighbor do those repos both have a `package.json` and include it in the jsdoc config? This code is working for me.

2019-07-24 12:53 UTC, crookedneighbor commented on publish.js
> +  var packageInfo = (find({kind: 'package'}) || [])[0];
They both do have package.json files. How are they supposed to be included in the jsdoc config? That may be the part I'm missing with this.

2019-07-24 15:55 UTC, rwwagner90 commented on publish.js
> +  var packageInfo = (find({kind: 'package'}) || [])[0];
@crookedneighbor we have it like this https://github.com/shipshapecode/shepherd/blob/master/.jsdoc.js#L10

2019-10-28 15:49 UTC, crookedneighbor commented
Sorry for leaving this open for so long. This change is not something we are looking to include in our use of this template, so we're going to close this PR. 

You are of course free to maintain your fork of the template with this change.

2019-10-28 15:49 UTC, closed without merging